# configs/governance_security/network_rules.yaml

#========================================================================
# SNOWFLAKE NETWORK RULES CONFIGURATION
#========================================================================

DBT_IP_US_ALLOWED:
  database: "PLATFORM_DATA_MANAGEMENT"
  schema: "DATA_GOVERNANCE"
  type: "IPV4"
  mode: "INGRESS"
  value_list:
    - "52.22.161.231"
    - "52.45.144.63"
    - "54.81.134.249"
  comment: "DBT (transformation tool) allowed IP addresses"

SPARK_NETWORK_IP_ALLOWED:
  database: "PLATFORM_DATA_MANAGEMENT"
  schema: "DATA_GOVERNANCE"
  type: "IPV4"
  mode: "INGRESS"
  value_list:
    - "219.88.198.160/29" # SparkBYOD MDR
    - "219.88.198.176/29" # SparkBYOD PAK
    - "122.57.19.32"      # Local IP retrieved with `curl ifconfig.me` command.