# configs/governance_security/schema_grants/dev_schema_grants.yaml

# This file defines the database grants for various roles in the system.
# Each entry specifies the database, schema, role, and the privilege granted to that role for the specified schema.
# The privileges can include "ALL PRIVILEGES", "USAGE", or other specific privileges as needed.

# DEV_RAW
- database: "DEV_RAW"
  schema: "LANDING"
  role: "DEV_INGESTION_ROLE"
  privilege: 
    - "USAGE"
    - "CREATE TABLE"
    - "CREATE VIEW"
    - "CREATE FILE FORMAT"
    - "CREATE STAGE"
    - "CREATE PIPE"
    - "CREATE SEQUENCE"
    - "CREATE FUNCTION"
    - "CREATE PROCEDURE"
    - "CREATE STREAM"
    - "CREATE TASK"
    - "CREATE MATERIALIZED VIEW"

- database: "DEV_RAW"
  schema: "LANDING"
  role: "DEV_TRANSFORMER_ROLE"
  privilege: 
    - "USAGE"

# DEV_ANALYTICS
- database: "DEV_ANALYTICS"
  schema: "STAGE"
  role: "DEV_TRANSFORMER_ROLE"
  privilege:
    - "USAGE"
    - "CREATE TABLE"
    - "CREATE VIEW"
    - "CREATE FILE FORMAT"
    - "CREATE STAGE"
    - "CREATE PIPE"
    - "CREATE SEQUENCE"
    - "CREATE FUNCTION"
    - "CREATE PROCEDURE"
    - "CREATE STREAM"
    - "CREATE TASK"
    - "CREATE MATERIALIZED VIEW"

- database: "DEV_ANALYTICS"
  schema: "INTERMEDIATE"
  role: "DEV_TRANSFORMER_ROLE"
  privilege: 
    - "USAGE"
    - "CREATE TABLE"
    - "CREATE VIEW"
    - "CREATE FILE FORMAT"
    - "CREATE STAGE"
    - "CREATE PIPE"
    - "CREATE SEQUENCE"
    - "CREATE FUNCTION"
    - "CREATE PROCEDURE"
    - "CREATE STREAM"
    - "CREATE TASK"
    - "CREATE MATERIALIZED VIEW"

- database: "DEV_ANALYTICS"
  schema: "MARTS"
  role: "DEV_TRANSFORMER_ROLE"
  privilege: 
    - "USAGE"
    - "CREATE TABLE"
    - "CREATE VIEW"
    - "CREATE FILE FORMAT"
    - "CREATE STAGE"
    - "CREATE PIPE"
    - "CREATE SEQUENCE"
    - "CREATE FUNCTION"
    - "CREATE PROCEDURE"
    - "CREATE STREAM"
    - "CREATE TASK"
    - "CREATE MATERIALIZED VIEW"

- database: "DEV_ANALYTICS"
  schema: "SNAPSHOT"
  role: "DEV_TRANSFORMER_ROLE"
  privilege: 
    - "USAGE"
    - "CREATE TABLE"
    - "CREATE VIEW"
    - "CREATE FILE FORMAT"
    - "CREATE STAGE"
    - "CREATE PIPE"
    - "CREATE SEQUENCE"
    - "CREATE FUNCTION"
    - "CREATE PROCEDURE"
    - "CREATE STREAM"
    - "CREATE TASK"
    - "CREATE MATERIALIZED VIEW"

- database: "DEV_ANALYTICS"
  schema: "MARTS"
  role: "DEV_REPORTING_ROLE"
  privilege: 
    - "USAGE"