output "fully_qualified_names" {
  description = "A map of network rule keys to their true fully qualified names generated by Snowflake"
  value = {
    for k, v in snowflake_network_rule.this : k => v.fully_qualified_name
  }
}