# configs/catalog/schemas/prod_analytics_schemas.yaml

- database: "PROD_ANALYTICS"
  name: "STAGE"
  comment: "Raw data landing zone for incoming data"
  data_retention_time_in_days: 0
  with_managed_access: true

- database: "PROD_ANALYTICS"
  name: "INTERMEDIATE"
  comment: "Transformed data for analytical use."
  data_retention_time_in_days: 0
  with_managed_access: true

- database: "PROD_ANALYTICS"
  name: "SNAPSHOT"
  comment: "Point-in-time copies of analytical data for historical analysis and reporting."
  data_retention_time_in_days: 0
  with_managed_access: true

- database: "PROD_ANALYTICS"
  name: "MARTS"
  comment: "Business-facing reporting layers and data marts (Gold layer)."
  data_retention_time_in_days: 0
  with_managed_access: true