# configs/envs/dev/governance_security/role_hierarchy.yaml

# This file defines the role hierarchy for the system.
# Each entry specifies a role and its parent role, establishing a hierarchy of roles.

# DEV ENVIRONMENT ROLES
- parent_role: "SYSADMIN"
  roles: 
    - "DEV_INGESTION_ROLE"
    - "DEV_TRANSFORMER_ROLE"
    - "DEV_REPORTING_ROLE"

# Database Role to Account Role Hierarchy
- parent_role: "DEV_TRANSFORMER_ROLE"
  database_name: "SNOWFLAKE"
  database_roles: 
    - "USAGE_VIEWER"
    - "DATA_METRIC_USER"
  