# configs/security/schema_grants.yaml

- database: "PROD_RAW"
  schema: "LANDING"
  role: "INGESTION_ROLE"
  privilege: "USAGE"

- database: "PROD_RAW"
  schema: "LANDING"
  role: "TRANSFORMER_ROLE"
  privilege: "USAGE"

- database: "PROD_ANALYTICS"
  schema: "CORE"
  role: "TRANSFORMER_ROLE"
  privilege: "ALL PRIVILEGES"

- database: "PROD_ANALYTICS"
  schema: "MARTS"
  role: "TRANSFORMER_ROLE"
  privilege: "ALL PRIVILEGES"

- database: "PROD_ANALYTICS"
  schema: "MARTS"
  role: "REPORTING_ROLE"
  privilege: "USAGE"