# configs/envs/dev/governance_security/schema_grants/schema_grants.yaml

# Snowflake commands to check the grants.
# SHOW FUTURE GRANTS IN SCHEMA DEV_RAW.LANDING;
# SHOW GRANTS TO ROLE DEV_TRANSFORMER_ROLE;

# Example of a schema grant with a permission set and custom overrides:
# - database: "DEV_RAW"
#   schema: "LANDING"
#   role: "DEV_TRANSFORMER_ROLE"
#   permission_set: "SCHEMA_READ"
#   custom_schema_privileges:
#     - "CREATE TAG"
#   custom_all_objects:
#     tables: ["DROP"]
#   custom_future_objects:
#     tables: ["DROP"]

# DEV_RAW
- database: "DEV_RAW"
  schema: "LANDING"
  role: "DEV_INGESTION_ROLE"
  permission_set: "SCHEMA_WRITE"

- database: "DEV_RAW"
  schema: "LANDING"
  role: "DEV_TRANSFORMER_ROLE"
  permission_set: "SCHEMA_READ"

# DEV_ANALYTICS
- database: "DEV_ANALYTICS"
  schema: "STAGE"
  role: "DEV_TRANSFORMER_ROLE"
  permission_set: "SCHEMA_WRITE"

- database: "DEV_ANALYTICS"
  schema: "INTERMEDIATE"
  role: "DEV_TRANSFORMER_ROLE"
  permission_set: "SCHEMA_WRITE"

- database: "DEV_ANALYTICS"
  schema: "MARTS"
  role: "DEV_TRANSFORMER_ROLE"
  permission_set: "SCHEMA_WRITE"

- database: "DEV_ANALYTICS"
  schema: "SNAPSHOT"
  role: "DEV_TRANSFORMER_ROLE"
  permission_set: "SCHEMA_WRITE"

- database: "DEV_ANALYTICS"
  schema: "MARTS"
  role: "DEV_REPORTING_ROLE"
  permission_set: "SCHEMA_READ"
