# configs/envs/prod/governance_security/role_hierarchy.yaml

# This file defines the role hierarchy for the system.
# Each entry specifies a role and its parent role, establishing a hierarchy of roles.

- PROD ENVIRONMENT ROLES
- parent_role: "SYSADMIN"
  roles: 
    - "PROD_INGESTION_ROLE"
    - "PROD_TRANSFORMER_ROLE"
    - "PROD_REPORTING_ROLE"

# Database Role to Account Role Hierarchy
- parent_role: "PROD_TRANSFORMER_ROLE"
  database_name: "SNOWFLAKE"
  database_roles: 
    - "USAGE_VIEWER"
    - "DATA_METRIC_USER"
  