# configs/governance_security/users.yaml

#========================================================================
# SNOWFLAKE USERS MANAGEMENT
#========================================================================

TRANSFORMER_SVC_USER:
  password: "ChangeMe123!"
  login_name: "TRANSFORMER_SVC_USER"
  display_name: "Transformer Service User"
  first_name: "Transformer"
  last_name: "Service User"
  email: ""
  must_change_password: false
  comment: "Service account for transformation pipelines - Restricted Network"
  disabled: false
  default_warehouse: "COMPUTE_WH"
  default_role: "DEV_TRANSFORMER_ROLE"
  # This explicitly binds custom policy to this user 
  network_policy: "GLOBAL_INGRESS_POLICY"