# configs/envs/dev/governance_security/database_grants/database_grants.yaml

# IMPORTANT: Check if your configuration references objects outside of the current environment. 
# For example, PLATFORM_DATA_MANAGEMENT.

# DEV_RAW
- database: "DEV_RAW"
  role: "DEV_INGESTION_ROLE"
  privilege: 
    - "USAGE"
    - "CREATE SCHEMA"
  all_schemas:
    - "USAGE"
  future_schemas:
    - "USAGE"

- database: "DEV_RAW"
  role: "DEV_TRANSFORMER_ROLE"
  privilege: 
    - "USAGE"
  all_schemas:
    - "USAGE"
  future_schemas:
    - "USAGE"

# DEV_ANALYTICS
- database: "DEV_ANALYTICS"
  role: "DEV_TRANSFORMER_ROLE"
  privilege: 
    - "USAGE"
    - "CREATE SCHEMA"
  all_schemas:
    - "USAGE"
  future_schemas:
    - "USAGE"

- database: "DEV_ANALYTICS"
  role: "DEV_REPORTING_ROLE"
  privilege: 
    - "USAGE"
  all_schemas:
    - "USAGE"
  future_schemas:
    - "USAGE"

# DEV roles for the PLATFORM_DATA_MANAGEMENT database
- database: "PLATFORM_DATA_MANAGEMENT"
  role: "DEV_INGESTION_ROLE"
  privilege: 
    - "USAGE"
  all_schemas:
    - "USAGE"
  future_schemas:
    - "USAGE"
    
- database: "PLATFORM_DATA_MANAGEMENT"
  role: "DEV_TRANSFORMER_ROLE"
  privilege: 
    - "USAGE"
  all_schemas:
    - "USAGE"
  future_schemas:
    - "USAGE"
    
- database: "PLATFORM_DATA_MANAGEMENT"
  role: "DEV_REPORTING_ROLE"
  privilege: 
    - "USAGE"
  all_schemas:
    - "USAGE"
  future_schemas:
    - "USAGE"