# configs/catalog/databases/prod_databases.yaml

- name: "PROD_RAW"
  comment: "Data Lake Landing Zone."
  is_transient: false
  data_retention_time_in_days: 14

- name: "PROD_ANALYTICS"
  comment: "Analytics Data Warehouse."
  is_transient: false
  data_retention_time_in_days: 14