# configs/envs/prod/governance_security/schema_grants/schema_grants.yaml

# Snowflake commands to check the grants.
# SHOW FUTURE GRANTS IN SCHEMA PROD_RAW.LANDING;
# SHOW GRANTS TO ROLE PROD_TRANSFORMER_ROLE;

# Example of a schema grant with a permission set and custom overrides:
# - database: "PROD_RAW"
#   schema: "LANDING"
#   role: "PROD_TRANSFORMER_ROLE"
#   permission_set: "SCHEMA_READ"
#   custom_schema_privileges:
#     - "CREATE TAG"
#   custom_all_objects:
#     tables: ["DROP"]
#   custom_future_objects:
#     tables: ["DROP"]

# PROD_RAW
- database: "PROD_RAW"
  schema: "LANDING"
  role: "PROD_INGESTION_ROLE"
  permission_set: "SCHEMA_WRITE"

- database: "PROD_RAW"
  schema: "LANDING"
  role: "PROD_TRANSFORMER_ROLE"
  permission_set: "SCHEMA_READ"

# PROD_ANALYTICS
- database: "PROD_ANALYTICS"
  schema: "STAGE"
  role: "PROD_TRANSFORMER_ROLE"
  permission_set: "SCHEMA_WRITE"

- database: "PROD_ANALYTICS"
  schema: "INTERMEDIATE"
  role: "PROD_TRANSFORMER_ROLE"
  permission_set: "SCHEMA_WRITE"

- database: "PROD_ANALYTICS"
  schema: "MARTS"
  role: "PROD_TRANSFORMER_ROLE"
  permission_set: "SCHEMA_WRITE"

- database: "PROD_ANALYTICS"
  schema: "SNAPSHOT"
  role: "PROD_TRANSFORMER_ROLE"
  permission_set: "SCHEMA_WRITE"

- database: "PROD_ANALYTICS"
  schema: "MARTS"
  role: "PROD_REPORTING_ROLE"
  permission_set: "SCHEMA_READ"
