# configs/catalog/databases/dev_databases.yaml

- name: "DEV_RAW"
  comment: "Data Lake Landing Zone."
  is_transient: true
  data_retention_time_in_days: 1

- name: "DEV_ANALYTICS"
  comment: "Analytics Data Warehouse."
  is_transient: true
  data_retention_time_in_days: 1